# -*- coding: utf-8 -*-

from . import models
from . import client
from . import AgenceBardo
from . import Agencecu
from . import dossier
from . import Abonnement
from . import admin
from . import coord
from . import demab
from . import historique
from . import coord1
from . import deposer
from . import modifier
from . import fiche
from . import suividossier
from . import contactus
from . import agence
from . import consultagence
from . import modif_agence
from . import consultfiche
from . import modif_fiche
from . import modifag
from . import coordag
from . import coordbardo
from . import modifb
from . import suivdoss
from . import contrat